version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: petar123
      POSTGRES_DB: player
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: petark123/kiiimage2:latest
    container_name: player-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/player
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: petar123
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_DATASOURCE_INITIALIZATION_MODE: always
      SPRING_DATASOURCE_PLATFORM: postgres
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
    depends_on:
      - db

volumes:
  postgres-data: