
apiVersion: apps/v1
kind: Deployment
metadata:
  name: players-deployment
  namespace: players
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: player-app
  template:
    metadata:
      labels:
        app: player-app
    spec:
      containers:
        - name: player-app
          image: petark123/kiiimage2:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: player-app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_H2_CONSOLE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: player-app-config
                  key: SPRING_H2_CONSOLE_ENABLED
            - name: SPRING_H2_CONSOLE_PATH
              valueFrom:
                configMapKeyRef:
                  name: player-app-config
                  key: SPRING_H2_CONSOLE_PATH
            - name: SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION
              valueFrom:
                configMapKeyRef:
                  name: player-app-config
                  key: SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION
            - name: SPRING_H2_CONSOLE_SETTINGS_TRACE
              valueFrom:
                configMapKeyRef:
                  name: player-app-config
                  key: SPRING_H2_CONSOLE_SETTINGS_TRACE
            - name: SPRING_SQL_INIT_MODE
              valueFrom:
                configMapKeyRef:
                  name: player-app-config
                  key: SPRING_SQL_INIT_MODE
            - name: SPRING_SQL_INIT_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: player-app-config
                  key: SPRING_SQL_INIT_PLATFORM
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: player-app-config
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: petar123
            # - name: SPRING_DATASOURCE_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: postgres-secret
            #       key: SPRING_DATASOURCE_USERNAME
            # - name: SPRING_DATASOURCE_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: postgres-secret
            #       key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
          livenessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 10
            periodSeconds: 10
            #Deployment