apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: players
type: Opaque
data:
  # postgres
  # petar123
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cGV0YXIxMjM=
