name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # You can change this to another distribution if needed

      - name: Build with Maven (skip tests)
        run: mvn -f ./pom.xml clean package -DskipTests # repo relative path

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kiiimage2:latest

  integration-test:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend]

    services:
      db:
        image: postgres:latest
        ports:
          - "5433:5432"
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: player
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: petar123

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn -f ./pom.xml clean package -DskipTests

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d
